cooler:
  schedule: "0/59 * * * * ? "
yapi:
  host: http://yapi.teamer.com.cn
  outputPath: /main/yapi
  adminUsername: bbcckkl@live.com
  adminPassword: me410231
http:
  connectTimeout: 60000

logging:
  level:
    root: info
  file: /main/yapi/logs/yapi-cooler.log
